# Copyright (c) 2026 enstarep <enstarep@rncyk.org> and other authors of stbdl
# License: https://github.com/theembodimentofdisharmony/stbdl/blob/main/LICENSE

from ctypes import wintypes
from typing import Optional

__version__: str

def window(path: Optional[str] = None, mode: int = 3) -> None: ...
def expansion() -> None: ...
def taskbar_switcher() -> wintypes.HWND: ...
def border(hwnd: wintypes.HWND) -> None: ...
def cleanup() -> bool: ...
